---
apiVersion: cluster.k8s.io/v1alpha1
kind: Machine
metadata:
  name: kubemark-actuator-testing-machine
  namespace: default
spec:
  providerSpec:
    value:
      apiVersion: kubemarkproviderconfig.k8s.io/v1alpha1
      kind: KubemarkMachineProviderConfig
      # turnUnhealthyAfter: true
      unhealthyDuration: 5s
      healthyDuration: 5s
      turnUnhealthyPeriodically: true
  versions:
    kubelet: 1.10.1
    controlPlane: 1.10.1
