---
apiVersion: cluster.k8s.io/v1alpha1
kind: Machine
metadata:
  name: minikube-static-machine
  namespace: kube-system
  annotations:
    cluster.k8s.io/static-machine: minikube
spec:
  providerSpec:
    value:
      apiVersion: kubemarkproviderconfig.k8s.io/v1alpha1
      kind: KubemarkMachineProviderConfig
  versions:
    kubelet: 1.10.1
    controlPlane: 1.10.1
